spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    active: dev
server:
  servlet-path: /api
  port: 1080
logging:
  level:
    org.springframework.security: ERROR
    org.springframework.boot.autoconfigure.security: ERROR